#!/command/with-contenv sh

export HOME=/home/homebridge
export USER=homebridge
export HOMEBRIDGE_CONFIG_UI=1

# this is not necessarily the ui version, it's now used as a feature compatibility indicator 
export CONFIG_UI_VERSION=4.44.2

 if [ "$PUID" = "0" ] || [ "$PGID" = "0" ]; then
   # the user wants homebridge to run as root
   exec /opt/homebridge/start.sh --allow-root
 else
   # standard operation, run as homebridge user (this could still be "root" if PUID and PGID are set to 0)
   exec s6-setuidgid $PUID:$PGID /opt/homebridge/start.sh
 fi
